file = open('data.txt','r')
data = file.readlines()
#print(data)
value = data[len(data)-1].split(',')
#print(value.split(','))
t = int(value[0].strip())
c = int(value[1].strip())
print(value[2].strip())
x = int(value[2].strip())
y = int(value[3].strip())
z = int(value[4].strip())
print(t,c,x,y,z)
file.close()
